version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh bash/start.sh
    env_file:
      - ./backend/.env
    ports:
      - 1337:1337
    depends_on:
      - db
      
  db:
    image: postgres:12.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432

volumes:
  postgres_data:
